### ISSUE TITLE
Health&Safety dump fail

### ISSUE THREAD

**Issue by Jimmy-Z** [d0k3/Hourglass9#10]
new 3DS JP, A9LH, 11.1, emuNAND just created (I intend to do a region change on this emuNAND)
I tried again on sysNAND, the same error

```
Initializing SD card... success
0x03 KeyX & KeyY: automatically set up
0x05 KeyY: automatically set up
0x25 KeyX: not found
0x18 KeyX: already set up
0x1B KeyX: not found
Finalizing Initialization...

Initialization: success!

Selected: [Health&Safety Dump]
Using EmuNAND @ 26C000/000000
Searching title "Health&Safety (N3DS)"...
Method 1: Search in title.db...
Method 2: Search in file system...
Found title 0004001020020300
TMD0 found at 111F0000, size 2916b
APP0 found at 11200000, size 900kB
APP1 found at 0E2D8000, size 156kB
Use arrow keys and <A> to choose a name
hs.app
Dumping & decrypting APP0...
Creating hs.app ...
Code / Crypto: CTR-N-HACJ / Secure3 
slot0x25KeyX not set up
This won't work on O3DS < 7.x or A9LH
Health&Safety Dump: failed!

Press B to return, START to reboot.
```

**Comment by Jimmy-Z** [comment]
Well I get that slot0x25KeyX.bin file and it works now, shouldn't that be like history now? Iast time I do A9LH on a friend's O3DS, it doesn't need this? it was 11.1 too.

**Comment by d0k3** [comment]
Depending on the entrypoint you use, your console type (O3DS/N3DS) and FW version, you may need that file or you may not need it.

If it asks you for that file, provide it. Nothing that can be done about it other than you putting in the effort. Closing this now.

**Comment by Jimmy-Z** [comment]
Good to know, thanks.
