### ISSUE TITLE
Another feature request: Convert installed titles to CIA

### ISSUE THREAD

**Issue by dlcopter** [d0k3/Hourglass9#11]
I really appreciate what Hourglass9 does. I'm not a big computer person, and I feel safe having it installed knowing that I won't brick my console using it. Adding the feature to convert installed titles to CIA would make it perfect for me. I know the ability has only just been added to Decrypt9, but I feel it would be good here too. I can't see a situation where having it would brick a 3DS, and it would add to H9's current ability to dump retail cartridges. Either way, thank you for what you do.

**Comment by violetkittygirl** [comment]
If it helps you feel more comfortable with using Decrypt9WIP, the only actions that you could perform that would break A9LH would be restoring a backup to sysNAND without '(Keep A9LH)' (preserving A9LH is silently enforced with Hourglass9) or injecting to partitions Sector0x96 or FIRM0/FIRM1 on sysNAND.

**Comment by d0k3** [comment]
I need to remind you the original focus of HG9 was just handling NAND backups (and nothing else). If I gradually take over D9 features, what will I have in the end? I'm still thinking about this feature request, though. In the meantime:

The fear you people got about using D9 is unfounded. For everything that can alter your SysNAND, you get a red warning and you have to enter a button sequence. For everything that can alter your A9LH installation, there is another red warning (different tint) and another button sequence. Even for EmuNAND altering operations, there is a yellow warning.

There is absolutely no way to run something dangerous accidentially in D9. Just read what is on screen, notice the colors and you are safe. Or, don't read it and you won't even know what button sequence to enter.

**Comment by d0k3** [comment]
Included in latest release
