### ISSUE TITLE
Cannot backup H&S or inject FBI on Korean New 3DS

### ISSUE THREAD

**Issue by novadaemon1** [d0k3/Hourglass9#16]
Tried to backup H&S on a Korean New 3DS. It will not backup. I cannot inject FBI.
Issue: Hourglass9 only tries to find title ID 0004001000027300 (I assume this is Korean Region Old 3DS.)
Solution: Hourglass9 needs to also find title ID 0004001020027300 (This is the title ID for the Korean New 3DS.)

**Comment by d0k3** [comment]
Try this test build and tell me if it works:
https://transfer.sh/KcbAJ/hourglass9-20170115-140420.zip
Fix coming in the next release

**Comment by novadaemon1** [comment]
It works perfectly for the New 3DS. On a side note, I don't know who's fault this is but HG9 does not think that the O3DS Korean Injectable FBI file is valid for the Korean O3DS. I can backup my H&S perfectly fine, I can inject an older version of FBI that I made myself, but the injectable file that comes in the FBI Injectable zip doesn't get seen by HG9.

I'm not sure if that's a HG9 issue or an issue with the FBI Injectable archive.

**Comment by d0k3** [comment]
Well... that is because the KOR injectable is not included in that ZIP file. Maybe ask @Plailect about it? Closing this issue now...
