### ISSUE TITLE
Is it possible to add Eshop game dump to H9?

### ISSUE THREAD

**Issue by Darkwolfdude** [d0k3/Hourglass9#18]
Hi, I'm a bit of a noob so I apologise in advanced as I don't 100% know what I'm doing.

I can see that Decrypt9 has the ability to turn downloaded games from the E-shop into .3ds games and was wondering if you could put that into Hourglass9, and have instructions on how to update. (Specifically .3ds for use with Citra - hopefully it will improve).

If this isn't possible, is there any details on how to run Decrypt9 to do so?

I have Luma, Hourglass9, "The Homebrew launcher" (it looks like smealums from booting into it), FBI.

I used https://3ds.guide/ to install CFW a week or so ago on my N3DSXL.

Thanks.

**Comment by d0k3** [comment]
Well... as always with requests such as this, if I gradually add features from D9 to HG9, what will we have in the end? I'm still thinking about it, though. Still, as you put it, why not use D9 for this? What you're searching for is the SD CXI dumper. All the info you need is in the readme, and if you need support, you can get that at the usual locations (GBAtemp, #3dshacks on Rizon, Github issues is not for support).

**Comment by Darkwolfdude** [comment]
I didn't really understand what to do with Decrypt9 as I could only see the linux build files - though I managed to find a link to the releases through elsewhere (and now I realise that it's just the same github address with /releases/ appended).

I also wasn't really sure what would work...

I have it working now, but the homebrew way didn't work for me. I hit up the Rizon IRC and someone told me that you have to do it through Luma after already having installed al9h. So I put the Decript9WIP.bin into the luma payloads folder and can run Decrypt9 without issues, thanks.

**Comment by d0k3** [comment]
Okay, thought about this, and I won't add it. If you need advanced features, use D9. HG9 is designed as a simple tool for inexperienced users, and blowing it up by adding features from D9 is against the HG9 philosophy.

tl;dtr - you need advanced features? Use D9.
