### ISSUE TITLE
Hourglass9 // Freezing // Not loading

### ISSUE THREAD

**Issue by perpetualhigh** [d0k3/Hourglass9#2]
Hello,

Posted on reddit and Plailect suggested I submit an issue here. Following the guide to a T and everything was going smoothly. 
https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)

Got to Part 5, Section IV: Held Start when Booting. It loads and says that Initialization: Success. Then, nothing happens. I can't control anything (tried all buttons). I figured it might be one of those random occurrences so I have tried again. Currently I have attempted this about 10-15 times. Every time it remains the same.

Here is what happens:
http://imgur.com/azZLfHE

I didn't want to do anything else at the moment as I treasure my device and would like to avoid a brick. In any case, Your assistance is truly appreciated. 

Here is some other background information:
Started the entire process on 6-5-2016
Followed the most current version of the guide.
System is a New 3DS XL. Began on Firmware 9.4 
Only ran into one hiccup in the entire process. Had to format and use a different SD card. I found this suggestion in the troubleshooting guide. Followed it. Everything else went smoothly. 

Thanks

**Comment by d0k3** [comment]
Here's a quick one you can try:
https://up1.ca/#GekZIPzH1-u6WG75iaPYPg
(don't worry, there is nothing dangerous in there) 

If that does not work, we need to try and find the issue. In that case I'll provide a new test build tomorrow (it is already pretty late here).

Also, don't be too worried. If you are using Hourglass9, your A9LH is already installed, which is basically a superpower against any brick. 

Additional info that could help would be SD card size and tools used to format.

**Comment by perpetualhigh** [comment]
Man, I appreciate how awesome you are d0k3! I just booted up this file and it loads now. I'm going to continue the guide with it and will update shortly. 

Thanks

**Comment by perpetualhigh** [comment]
Oh to address your questions on the SD card.

I started out using a SanDisk 32GB - I used the recommended tool in the guide to format (guiformat.exe) This card gave me issues at one point. I forget which part, but basically I was getting dual black screens. 

I'm now using a SanDisk 8GB - also formatted with guiformat.exe. Was able to continue the guide and is what I am currently using at the moment to install. Hope to change over to a 32 or 64GB after all the installations finalize. 

Was planning on using USB Image Tool to backup and restore the SD cards once all is said and done.

**Comment by d0k3** [comment]
Alright, good to know it worked - the fix will be in the next release version for everyone! On a sidenote - you wouldn't have had this problem if you formatted with EmuNAND9 (it was still a bug in HourGlass9, so it had to be fixed here). When you switch back, I'd still suggest using EmuNAND9 to format it, even if you don't use EmuNAND ("Format with no EmuNAND"). Don't use a USB imaging tool either, just copy the SD files to you harddrive and back.

Closing this now, have fun!
