### ISSUE TITLE
Add datestamp option for NAND backups

### ISSUE THREAD

**Issue by edwinsage** [d0k3/Hourglass9#21]
One of the naming options for NAND dumps should  be something like "NANDmin-2017-02-18-14:25:32.bin", or even just something like "NANDmin-02.18-1425.bin".  Something with a datestamp, to make keeping track of backups easier.  Naturally, the backup restorer should find files matching the pattern too.

**Comment by d0k3** [comment]
Has been asked several times before, but there is no access to the internal clock on ARM9, so this is not possible. You will have to do that manually. You can, howerver, use the existing naming options to number your backups in chronological order.
