### ISSUE TITLE
can't dump 11.3U Hs.app

### ISSUE THREAD

**Issue by Leerz** [d0k3/Hourglass9#23]
can't dump 11.3U Hs.app

following the guide, godmode9 inject .app of FBI didn't work

so i tried the old way which is through dump hourglass9 then inject the fbi injectable .app

returned:
code / crypto: ctr-n-hace / 7x
slot0x25keyx not setup
this won't work on o3ds < 7x or a9lh

health & safety dump: failed

Details:
System is a freshly downgraded 11.3U (successfully installed a9lh+luma)

thanks

**Comment by d0k3** [comment]
You're missing slot0x25keyX.bin or aeskeydb.bin. Read the guide more thoroughly.

**Comment by Leerz** [comment]
Thanks, i posted this godmode9, and you answered already so it was fixed, i was using a defunct version of the aeskeydb 

Thank you
