### ISSUE TITLE
Boot9Strap compatibility

### ISSUE THREAD

**Issue by IngeniousDefault** [d0k3/Hourglass9#24]
Hi there.

After the release of B9S Hourglass9 does not work anymore with this setting. Will you update H9 for B9S? Another small question: Are old backups that were created with H9 and A9LH still working if I inject them with GodMode9 and B9S? Will those remove B9S and/or re-install A9LH?

EDIT: Thanks for the release. I noticed however that Hourglass9 still says that it's running from A9LH in System Info. Nothing major but I thought I should mention it here.

**Comment by d0k3** [comment]
Backups work the same as before, A9LH preserving actually preserves sighax, too. Leaving this open cause you are right about System Info. Maybe someone wants to do a pull request for that? Also the text of the preserving NAND restore maybe? Or readme?

**Comment by FateForWindows** [comment]
Repo description still says A9LH-only.

**Comment by d0k3** [comment]
Okay, already changed it. Readme is still not up to date. As I said, a new maintainer would be appreciated.
