### ISSUE TITLE
Hourglass9 won't boot

### ISSUE THREAD

**Issue by RenegadeRaven** [d0k3/Hourglass9#25]
Whenever I try to use Hourglass9, it gives me the error in the image below.
![2017-06-05 01 37 55](https://cloud.githubusercontent.com/assets/8683689/26773253/147efed8-4990-11e7-9919-65e274f23536.jpg)

**Comment by d0k3** [comment]
That's an issue with old HG9 code and boot9strap v1.1+ code.

It's actually easily done, see here:
d0k3/GodMode9@d8d2901
d0k3/GodMode9@540daed

I do take pull requests, otherwise it's when / if I get to it.

**Comment by Freeglobe** [comment]
do you release a new version, soon?

**Comment by d0k3** [comment]
Fixed in most recent commit, get the hourly from the hourlies page if you want.

d0k3.secretalgorithm.com
