### ISSUE TITLE
No install instructions

### ISSUE THREAD

**Issue by savoca** [d0k3/Hourglass9#26]
release tags include .hex and .bin files but are they supposed to be dropped in the root of the sdcard or into abc/xyz/idontwritedocs/installdir/file.hex? dead project or is there a buried install guide....

**Comment by d0k3** [comment]
This is deprecated. Use GodMode9 like everyone else :^). Or, use fastboot3DS (installed via [OpenFirmInstaller](https://github.com/d0k3/OpenFirmInstaller)) as your bootloader.
