### ISSUE TITLE
Feature request: Add NCCH Padgen to Hourglass9

### ISSUE THREAD

**Issue by Hellrespawn** [d0k3/Hourglass9#3]
As per the title.

Then laymen would still have the option of dumping their cartridges without the risk of bricking, which would go well with Plailect's guide.

**Comment by d0k3** [comment]
If I gradually add back in D9 features, what will we have in the end? (Hint: it starts with 'Decrypt' and ends with '9'.

'Bricking risk' is vastly overestimated, too. You will have a hard time accidentially bricking with D9 (so far there is no known case of anyone managing to do this). The only imaginable way of actually bricking is via deliberate injection of corrupted (in a certain way) CTRNAND partitions or injection of corrupted certain files.

Also, take note that NCCH padgen is a legacy feature, only there to allow following old tutorials. The NCCH decryptor is the way to go. Thus NCCH padgen will not be added to this. I will consider adding the decryptor right into uncart, though.
