### ISSUE TITLE
Hourglass9 frozen at the beginning.

### ISSUE THREAD

**Issue by Supertatortots** [d0k3/Hourglass9#4]
Hello, I've been following part 5 of the guide and so far I've had no notable issues up until this point.

https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)#section-iv---copying-rednand-data-to-sysnand

When I boot up Hourglass9, it gets stuck at

```

Counting 2 submenus and 9 features
Initializing, hold L+R to pause
Checking arm9loaderhax... success
```

But then freezes and doesn't move at all.  Triple checked if I have everything installed and everything seems good. 

Using a 32GB Sony SD card by the way. 

Thanks for any help you can give me.

**Comment by Masamune3210** [comment]
which version of the data_input and payload_input packages are you using

**Comment by astronautlevel2** [comment]
Newest a9lh payloads seem to break d0k3's tools. I'm not sure what the best course of action from here is :confused:

**Comment by Supertatortots** [comment]
https://www.reddit.com/r/3dshacks/comments/4n695x/safea9lhinstaller_v20_released_new_key2_different/

Yeah, I just found that out. At least it's not this then. 

Guess I'll have to be patient and wait for a fix.

**Comment by d0k3** [comment]
This is already fixed, closing it now
