### ISSUE TITLE
hourglass can't start

### ISSUE THREAD

**Issue by iamapie13** [d0k3/Hourglass9#5]
it says that "0x05 key Y" and 0x1B key X" were not found and it says Initialization failed!

**Comment by d0k3** [comment]
Update to the most recent version (v1.10) and tell me if it works:
https://github.com/d0k3/Hourglass9/releases

 If not - is there anything special about your a9lh installation?

**Comment by iamapie13** [comment]
I was using the latest version and it kept giving me the same error, I used Decrypt9 instead to restore my nand without loosing a9lh and after that it worked normally
