### ISSUE TITLE
[BUG] EmuNAND cannot backup due to file size. But i have enough space.

### ISSUE THREAD

**Issue by jackomix** [d0k3/Hourglass9#6]
I have 1.87 GB free on my SD card. But Hourglass9 says my 943MB sized emunand can't backup. Is this normal?

**Comment by d0k3** [comment]
The SD i/o routines dislike certain kinds of formatting. I'd suggest you do the backup on PC (with Multi EmuNAND Creator, f.e.), then use another SD or format this one fresh with EmuNAND9 or GodMode9 - does this solve the problem?

**Comment by jackomix** [comment]
Okay, i got my backup. But it didn't give me a .sha file. Is this normal? Is it important?

**Comment by jackomix** [comment]
Okay, after jumping over a risk i got A9LH! :D Thanks SO much for creating something that made the guide so easy you could do a speedrun and get 20 or 30 minutes. Thanks! :D

**Comment by d0k3** [comment]
If you don't have an sha file, that's not a problem, but I guess you already saw that. So... Issue solved? If so, please close!

**Comment by jackomix** [comment]
How do i close this?

EDIT: Wait nvm. Thanks! :D
