### ISSUE TITLE
When backing up NAND, move free space check to after filename pick

### ISSUE THREAD

**Issue by JohnVeness** [d0k3/Hourglass9#7]
Hi,

This issue probably applies to D9 too but I haven't checked.

I wanted to backup my NAND in H9, overwriting an older backup. When you pick which filename to backup to in H9, it shows (!) next to filenames of existing backups and warns you, which is fine. However, if the SD card is nearly full, it will not allow you to backup at all, even if you wanted to overwrite an older backup.

I suggest moving the free space check to after the filename is picked, and after the warning about overwriting is confirmed, so that the user can overwrite an existing backup even if free space is low.

**Comment by d0k3** [comment]
Agreed, and changed for Decrypt9WIP & HourGlass9
