### ISSUE TITLE
Remove EmuNAND menu programmatically, or separate version?

### ISSUE THREAD

**Issue by JohnVeness** [d0k3/Hourglass9#8]
I like how H9 is a cut-down, noob-friendly version of D9. However, for people who follow the Plailect guide, they won't have an EmuNAND, so the EmuNAND menu is redundant and possibly confusing.

Is it possible to H9 to detect in the code whether an EmuNAND partition exists, and only show the menu if so?

If not, is it possible to make a separate version of H9 that doesn't include the EmuNAND feature, that could be linked to from the Plailect guide and similar?

**Comment by d0k3** [comment]
Although this is not a bad idea, if I start there, I'd also have to disable the the Gamecart Dumper menu when no game cartridge is inserted, disable the NAND Restore entry when no valid NAND dump is found, etc...

Every user using my tools should know of the difference between EmuNAND and SysNAND. Also, even if you accidentially select an EmuNAND menu entry with no EmuNAND actually set up, you will just get an error message and nothing bad will happen.
