### ISSUE TITLE
Include versions, serial numbers, dates etc. in NAND dump filenames

### ISSUE THREAD

**Issue by JohnVeness** [d0k3/Hourglass9#9]
(Again, this probably applies to Decrypt9WIP too).

Having used Hourglass9 quite a lot recently, on a couple of different 3DSes, it strikes me that the current selection of different filenames to pick when dumping NANDs is quite limited, even with the ability to choose NAND1.bin, NAND2.bin etc. Unless I rename them soon after, I can get confused as to which 3DS this is from, which firmware version and (where both of those are the same) when it was dumped. It would be great if the serial number of the 3DS (assuming this can be determined automatically), the firmware version, and a date, could be added to the filename. It would also be useful to add custom text, such as "after CTRNAND downgrade" or "before format" etc.

I realise this will quite a challenge in the UI, especially if these different elements are to be optional

**Comment by JohnVeness** [comment]
(I would suggest a v1 implementation would be to _not_ make serial/firmware ver/date optional, and see if anyone complains!)

A similar argument can be made when dumping hs.app, which again could benefit from having a version number, and whether it's from an o3DS or n3DS.

**Comment by james-d-elliott** [comment]
May be ideal to move the hash into an "info" file of some kind with this information. Ideally if implimented it would be ideal to format the serial number with red/green depending on if the serial matches the running unit. So have your FIRM.bin with FIRM.info. In the .info file a simple line by line information list (date can probably be found via created date, unless the 3DS doesn't support this feature):

md5 1a79a4d60de6718e8e5b326e338ae533
sha1 cf23df2207d99a74fbe169e3eba035e633b65d94
serial QAH000000001
firm 9.2.0-20

**Comment by JohnVeness** [comment]
Yes, that could be one way of doing it, but the idea of encoding this in the filename makes it easier to see at a glance (e.g. if all files are backed up on a PC, not just in the Hourglass9 UI) which file is which. It also prevents filename clashes, i.e. I could keep all NAND dumps in one folder, rather than what I do at the moment of manually making a subfolder for each, with a description in the folder name.

Regarding the NAND file creations date in the FAT filesystem, they always seem to be the same date for me, as if Hourglass9 can't read the 3DS clock

**Comment by Masamune3210** [comment]
Idk if any arm9 payload can read the clock, since they are launched before even the firm is booted.

**Comment by d0k3** [comment]
This is not a too common problem, as most people will only own one unit, and even if they do own multiple units, all of these units will have their own SD card (meaning to have them all in one place you'd have to move them over to PC anyways). Also - you know a NAND backup can only be restored on the unit it came from?

As for the ideas in this posting:
Serial number: Would actually be possible, but see above. Also, I guarantee you, this would do more bad than good in terms of confusion.
FIRM version: Not possible without a hardcoded list of FIRM SHAs (which I don't want in my software).
Date / time: Not possible, no access to clock.
Adding custom text: I won't do a onscreen keyboard for ARM9 or button text input scheme. Too much of a pita for too little gain.

As for more specific filenames for hs.app - this would actually be possible here, but there is no good way of handling specific hs.app filenames in UIG, so better not. Also, the last update to Health & Safety was on 6.x for O3DS units. For N3DS units that last update was on 9.1 (for Japan N3DS units) and there is only one version for all other regions. In short: not worth it.

I'd personally like to have dates in the dumped filenames, though, and once that possibility opens up I may implement it. For now, I'll close this issue.
